apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-processor
  template:
    metadata:
      labels:
        app: spark-processor
    spec:
      containers:
      - name: spark-processor
        image: wellstream-spark:latest # Assumes a pre-built image
        imagePullPolicy: IfNotPresent # Use local image
        ports:
        - containerPort: 4040
          name: metrics
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker:9092"
